// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class IndexhtmlTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void indexhtml() {
    driver.get("http://104.40.150.146/login?nextPath=%2F");
    driver.manage().window().setSize(new Dimension(924, 728));
    driver.findElement(By.name("login")).click();
    driver.findElement(By.name("login")).sendKeys("anikita373");
    driver.findElement(By.name("password")).sendKeys("qwe123QWE!@#");
    driver.findElement(By.cssSelector(".btn")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Перейти к списку игр")).click();
    vars.put("win988", waitForWindow(200000));
    driver.switchTo().window(vars.get("win988").toString());
    driver.findElement(By.linkText("Создать Игру")).click();
    driver.findElement(By.name("gname")).click();
    driver.findElement(By.name("gname")).sendKeys("test");
    driver.findElement(By.id("btn-new-game")).click();
    driver.findElement(By.cssSelector("html")).click();
  }
}
