// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void () {
    driver.get("http://104.40.150.146/login?nextPath=%2F");
    driver.manage().window().setSize(new Dimension(924, 728));
    driver.findElement(By.linkText("Регистрация здесь")).click();
    driver.findElement(By.name("login")).click();
    driver.findElement(By.name("login")).sendKeys("kavo123456783");
    driver.findElement(By.name("nativeName")).click();
    driver.findElement(By.name("nativeName")).sendKeys("Аааа Ааааа");
    driver.findElement(By.name("passwd")).click();
    driver.findElement(By.name("passwd")).click();
    driver.findElement(By.name("passwd")).sendKeys("qwe123QWE!@#");
    driver.findElement(By.cssSelector(".container:nth-child(2)")).click();
    driver.findElement(By.name("rpasswd")).click();
    driver.findElement(By.name("rpasswd")).sendKeys("qwe123QWE!@#");
    driver.findElement(By.cssSelector(".btn")).click();
    assertThat(driver.findElement(By.cssSelector(".alert-success")).getText(), is("Пользователь kavo123456783 был успешно зарегестрирован в системе."));
  }
}
